---
- name: Restart docker
  systemd:
    name: docker
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart homer
  systemd:
    name: homer
    state: restarted

- name: Restart radarr
  systemd:
    name: radarr
    state: restarted

- name: Restart sonarr
  systemd:
    name: sonarr
    state: restarted

- name: Restart prowlarr
  systemd:
    name: prowlarr
    state: restarted
