---
- name: Restart docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart radarr
  become: true
  ansible.builtin.systemd:
    name: radarr
    state: restarted

- name: Restart sonarr
  become: true
  ansible.builtin.systemd:
    name: sonarr
    state: restarted

- name: Restart prowlarr
  become: true
  ansible.builtin.systemd:
    name: prowlarr
    state: restarted

- name: Restart qbittorrent
  become: true
  ansible.builtin.systemd:
    name: qbittorrent
    state: restarted

- name: Restart jellyfin
  become: true
  ansible.builtin.systemd:
    name: jellyfin
    state: restarted

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
