---
- name: Create systemd unit file
  become: true
  ansible.builtin.template:
    src: container.service.j2
    dest: /etc/systemd/system/{{ item.key }}.service
    mode: 0644
  vars:
    container: "{{ item.value | combine({'name': item.key}) }}"
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Restart {{ item.key }}

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Pull image
  become: true
  community.docker.docker_image:
    name: "{{ item.value.container_image }}"
    state: present
    source: pull
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Restart {{ item.key }}

- name: Start and enable service
  become: true
  ansible.builtin.systemd:
    name: "{{ item.key }}"
    state: started
    enabled: true
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"
