---
- name: Check if jellyfin system config file exists
  ansible.builtin.stat:
    path: /data/state/jellyfin/config/system.xml
  register: jellyfin_system_config_file

- name: Create jellyfin system config file
  ansible.builtin.copy:
    dest: /data/state/jellyfin/config/system.xml
    content: "<ServerConfiguration/>"
    mode: 0600
  when: not jellyfin_system_config_file.stat.exists
  notify: Restart jellyfin

- name: Enable jellyfin metrics
  community.general.xml:
    path: /data/state/jellyfin/config/system.xml
    xpath: /ServerConfiguration/EnableMetrics
    value: "true"
  notify: Restart jellyfin

- name: Check if jellyfin network config file exists
  ansible.builtin.stat:
    path: /data/state/jellyfin/config/network.xml
  register: jellyfin_network_config_file

- name: Create jellyfin network config file
  ansible.builtin.copy:
    dest: /data/state/jellyfin/config/network.xml
    content: "<NetworkConfiguration/>"
    mode: 0600
  when: not jellyfin_network_config_file.stat.exists
  notify: Restart jellyfin

- name: Enable jellyfin metrics
  community.general.xml:
    path: /data/state/jellyfin/config/network.xml
    xpath: /NetworkConfiguration/BaseUrl
    value: "/jellyfin"
  notify: Restart jellyfin

- name: Configure jellyfin logging
  ansible.builtin.copy:
    src: jellyfin.logging.json
    dest: /data/state/jellyfin/config/logging.default.json
    mode: 0600
  notify: Restart jellyfin
