---
- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: Configure docker
  copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
    - Restart docker

- name: Install the datadog agent
  include_role:
    name: datadog.datadog
  vars:
    datadog_additional_groups:
      - adm
      - docker
      - systemd-journal
    datadog_config:
      logs_enabled: true
      listeners:
        - name: docker
      config_providers:
        - name: docker
          polling: true
      logs_config:
        container_collect_all: true
      process_config:
        enabled: true
      apm_config:
        enabled: false
    datadog_checks:
      auth:
        logs:
          - type: file
            path: /var/log/auth.log
            service: auth
            source: auth
      cloud-init:
        logs:
          - type: file
            path: /var/log/cloud-init.log
            service: cloud-init
            source: cloud-init
            start_position: beginning
            log_processing_rules:
              - type: multi_line
                name: new_log_start_with_date
                pattern: \d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}
      container:
      disk:
        instances:
      docker:
      journald:
        logs:
          - type: journald
            container_mode: true
            exclude_units:
              - homer.service
              - radarr.service
              - sonarr.service
              - qbittorrent.service
              - prowlarr.service
              - jellyfin.service
      systemd:
        init_config:
        instances:
          - unit_names:
              - cron.service
              - datadog-agent.service
              - docker.service
              - docker.socket
              - ssh.service
              - unattended-upgrades.service

- name: Create homer config directory
  file:
    path: /etc/homer
    state: directory

- name: Create homer config file
  template:
    src: homer.yml.j2
    dest: /etc/homer/config.yml
  notify: Restart homer

- name: Create and configure containers
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    service_name: "{{ item.name }}"
    container_name: "{{ item.name }}"
    container_image: "{{ item.image }}:{{ item.version }}"
    container_labels:
      - com.datadoghq.tags.env=prod
      - com.datadoghq.tags.service={{ item.name }}
      - com.datadoghq.tags.version={{ item.version }}
    container_docker_pull: true
    container_ports: "{{ item.ports | default([]) }}"
    container_env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
    container_volumes: "{{ item.volumes | default([]) + ['/etc/localtime:/etc/localtime:ro'] }}"
  loop: "{{ containers }}"
