---
- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: Configure docker
  copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
    - Restart docker

- name: Install the datadog agent
  include_role:
    name: datadog.datadog
  vars:
    datadog_api_key: "{{ secrets.api_keys['datadog'] }}"
    datadog_additional_groups:
      - adm
      - docker
      - systemd-journal
    datadog_config:
      logs_enabled: true
      listeners:
        - name: docker
      config_providers:
        - name: docker
          polling: true
      logs_config:
        container_collect_all: true
      process_config:
        enabled: true
      apm_config:
        enabled: false
    datadog_checks:
      auth:
        logs:
          - type: file
            path: /var/log/auth.log
            service: auth
            source: auth
      cloud-init:
        logs:
          - type: file
            path: /var/log/cloud-init.log
            service: cloud-init
            source: cloud-init
            start_position: beginning
            log_processing_rules:
              - type: multi_line
                name: new_log_start_with_date
                pattern: \d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\,\d{3}
      container:
      disk:
        instances:
      docker:
      journald:
        logs:
          - type: journald
            container_mode: true
            exclude_units:
              - homer.service
              - radarr.service
              - radarr-exportarr.service
              - sonarr.service
              - sonarr-exportarr.service
              - qbittorrent.service
              - prowlarr.service
              - jellyfin.service
      systemd:
        init_config:
        instances:
          - unit_names:
              - cron.service
              - datadog-agent.service
              - docker.service
              - docker.socket
              - ssh.service
              - unattended-upgrades.service
      openmetrics:
        init_config:
        instances:
          - openmetrics_endpoint: http://localhost:9707/metrics
            namespace: sonarr
            raw_metric_prefix: sonarr_
            metrics:
              - .+
          - openmetrics_endpoint: http://localhost:9708/metrics
            namespace: radarr
            raw_metric_prefix: radarr_
            metrics:
              - .+

- name: Create config directories
  file:
    path: /etc/{{ item.key }}
    state: directory
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create homer config file
  template:
    src: homer.yml.j2
    dest: /etc/homer/config.yml
  notify: Restart homer

- name: Create nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Create config files
  template:
    src: config.xml.j2
    dest: /etc/{{ item.key }}/config.xml
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"
  when: "'xml_config' in item.value.flags"
  notify: Restart {{ item.key }}

- name: Create a network
  docker_network:
    name: mediaserver
    driver: bridge
    state: present

- name: Create and configure containers
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    service_name: "{{ item.key }}"
    container_name: "{{ item.key }}"
    container_image: "{{ item.value.image }}:{{ item.value.version }}"
    container_labels:
      - com.datadoghq.tags.env=prod
      - com.datadoghq.tags.service={{ item.key }}
      - com.datadoghq.tags.version={{ item.value.version }}
    container_docker_pull: true
    container_ports:
      - "{{ item.value.port }}:{{ item.value.port }}"
    container_network: "mediaserver"
    container_env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
      WEBUI_PORTS: "{{ containers.qbittorrent.port }}"
    container_volumes: "{{ item.value.volumes | default([]) + ['/etc/localtime:/etc/localtime:ro'] }}"
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create and configure exportarr containers
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    service_name: "{{ item.key }}-exportarr"
    container_name: "{{ item.key }}-exportarr"
    container_image: "{{ exportarr.image }}:{{ exportarr.version }}"
    container_labels:
      - com.datadoghq.tags.env=prod
      - com.datadoghq.tags.service={{ item.key }}-exportarr
      - com.datadoghq.tags.version={{ exportarr.version }}
    container_docker_pull: true
    container_cmd:
      - "{{ item.key }}"
    container_ports:
      - "127.0.0.1:{{ item.value.exportarr.port }}:{{ item.value.exportarr.port }}"
    container_network: "mediaserver"
    container_env:
      PORT: "{{ item.value.exportarr.port }}"
      URL: "http://{{ item.key }}:{{ item.value.port }}/{{ item.key }}"
      APIKEY: "{{ secrets.api_keys[item.key] }}"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
    container_volumes:
      - /etc/localtime:/etc/localtime:ro
  with_dict: "{{ containers }}"
  loop_control:
    label: "{{ item.key }}"
  when: "'exportarr' in item.value.flags"
