---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx

- name: Create static assets directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  with_items:
    - /var/www/html
    - /var/www/html/homer
    - /var/www/html/theme.park

- name: Install homer assets
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/bastienwirtz/homer/releases/download/v23.02.2/homer.zip
    dest: /var/www/html/homer
    remote_src: "yes"
    owner: www-data
    group: www-data

- name: Create homer config file
  become: true
  ansible.builtin.template:
    src: homer.yml.j2
    dest: /var/www/html/homer/assets/config.yml
    mode: 0600
    owner: www-data
    group: www-data

- name: Download theme.park CSS themes
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/themepark-dev/theme.park/archive/refs/tags/{{ themepark.version }}.zip
    dest: /var/www/html/theme.park
    remote_src: "yes"
    owner: www-data
    group: www-data

- name: Remove default site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Copy mediaserver site config
  become: true
  ansible.builtin.template:
    src: mediaserver.conf.j2
    dest: /etc/nginx/sites-available/mediaserver.conf
    mode: 0600
  notify: Restart nginx

- name: Enable mediaserver site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mediaserver.conf
    dest: /etc/nginx/sites-enabled/mediaserver.conf
    state: link
  notify: Restart nginx
