---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Download datadog nginx tracing module
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/DataDog/nginx-datadog/releases/download/v1.0.4/nginx_{{ ansible_facts.packages.nginx[0].version | split('-') | first }}-arm64-ngx_http_datadog_module.so.tgz"
    dest: /usr/lib/nginx/modules
    remote_src: "yes"
    owner: root
    group: root
  notify: Restart nginx

- name: Copy datadog nginx tracing module config
  become: true
  ansible.builtin.copy:
    src: mod-http-datadog.conf
    dest: /usr/share/nginx/modules-available/
    mode: 0644
  notify: Restart nginx

- name: Enable datadog nginx tracing module
  become: true
  ansible.builtin.file:
    src: /usr/share/nginx/modules-available/mod-http-datadog.conf
    dest: /etc/nginx/modules-enabled/10-mod-http-datadog.conf
    state: link
  notify: Restart nginx

- name: Create static assets directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  with_items:
    - /var/www/html
    - /var/www/html/datadog
    - /var/www/html/homer

- name: Install homer assets
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/bastienwirtz/homer/releases/download/v{{ homer.version }}/homer.zip
    dest: /var/www/html/homer
    remote_src: "yes"
    owner: www-data
    group: www-data

- name: Create homer config file
  become: true
  ansible.builtin.template:
    src: homer.yml.j2
    dest: /var/www/html/homer/assets/config.yml
    mode: 0600
    owner: www-data
    group: www-data

- name: Download theme.park CSS themes
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/themepark-dev/theme.park/archive/refs/tags/{{ themepark.version }}.zip
    dest: /var/www/html
    include:
      - "*.css"
    remote_src: "yes"
    owner: www-data
    group: www-data

- name: Download datadog RUM script
  become: true
  ansible.builtin.get_url:
    url: https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js
    dest: /var/www/html/datadog/rum.js
    mode: 0600
    owner: www-data
    group: www-data

- name: Remove default site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Copy mediaserver site config
  become: true
  ansible.builtin.template:
    src: mediaserver.conf.j2
    dest: /etc/nginx/sites-available/mediaserver.conf
    mode: 0600
  notify: Restart nginx

- name: Enable mediaserver site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mediaserver.conf
    dest: /etc/nginx/sites-enabled/mediaserver.conf
    state: link
  notify: Restart nginx
