---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx

- name: Create static assets directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Install homer assets
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/bastienwirtz/homer/releases/download/v23.02.2/homer.zip
    dest: /var/www/html
    remote_src: "yes"
    owner: www-data
    group: www-data

- name: Create homer config file
  become: true
  ansible.builtin.template:
    src: homer.yml.j2
    dest: /var/www/html/assets/config.yml
    mode: 0600
    owner: www-data
    group: www-data

- name: Remove default site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Copy mediaserver site config
  become: true
  ansible.builtin.template:
    src: mediaserver.conf.j2
    dest: /etc/nginx/sites-available/mediaserver.conf
    mode: 0600
  notify: Restart nginx

- name: Enable mediaserver site
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mediaserver.conf
    dest: /etc/nginx/sites-enabled/mediaserver.conf
    state: link
  notify: Restart nginx
